export interface StoreLocation {
  id: string;
  name: string;
  type: 'supermarket' | 'local-shop' | 'market' | 'specialty';
  city: string;
  address: string;
  coordinates: {
    lat: number;
    lng: number;
  };
  phone?: string;
  workingHours: string;
  products: string[]; // product IDs from products-data
  description?: string;
}

export const stores: StoreLocation[] = [
  // София - множество магазини
  {
    id: 'lyulin-501-539',
    name: 'Магазин Люлин',
    type: 'local-shop',
    city: 'София',
    address: 'ж.к. Люлин, ул. 501, бл. 539, вх. А',
    coordinates: { lat: 42.715, lng: 23.245 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
    description: 'Пресни млечни продукти всеки ден',
  },
  {
    id: 'lyulin-service-west',
    name: 'Service West',
    type: 'local-shop',
    city: 'София',
    address: 'ж.к. Люлин, ул. 501, Service West, бл. 544',
    coordinates: { lat: 42.716, lng: 23.247 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'lyulin-momko',
    name: 'Магазин Люлин 10',
    type: 'local-shop',
    city: 'София',
    address: 'ж.к. Люлин 10, ул. Момко',
    coordinates: { lat: 42.72, lng: 23.25 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'lyulin-1-bl25',
    name: 'Магазин Люлин 1',
    type: 'local-shop',
    city: 'София',
    address: 'ж.к. Люлин 1, до бл. 25',
    coordinates: { lat: 42.71, lng: 23.24 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'chepintsi-vitosha',
    name: 'Маркет Витоша',
    type: 'local-shop',
    city: 'София',
    address: 'Кв. Чепинци, ул. Възрожденска 29',
    coordinates: { lat: 42.65, lng: 23.3 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo', 'izvara'],
  },
  {
    id: 'banishora-aro',
    name: 'Магазин АРО',
    type: 'local-shop',
    city: 'София',
    address: 'ж.к. Банишора, ул. Ген. Столетов 104',
    coordinates: { lat: 42.715, lng: 23.31 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'razadnika-steven-87',
    name: 'Магазин Стивън',
    type: 'local-shop',
    city: 'София',
    address: 'ж.к. Разсадника, бл. 87, вх. 2',
    coordinates: { lat: 42.69, lng: 23.35 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'zona-b5-steven',
    name: 'Магазин Стивън',
    type: 'local-shop',
    city: 'София',
    address: 'Зона Б5, бул. Стамболийски 182',
    coordinates: { lat: 42.7, lng: 23.31 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'svoge-farduv',
    name: 'Магазин Фърдов и синове',
    type: 'local-shop',
    city: 'Своге',
    address: 'ул. Джиджовска 2',
    coordinates: { lat: 42.9667, lng: 23.35 },
    phone: '+359 885 911 999',
    workingHours: 'Пон-Съб 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo', 'izvara'],
  },
  {
    id: 'elin-pelin-krasi',
    name: 'Магазин Краси 08',
    type: 'local-shop',
    city: 'Елин Пелин',
    address: 'ул. Средна гора, кв. 17',
    coordinates: { lat: 42.6667, lng: 23.6 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Пловдив - множество магазини
  {
    id: 'plovdiv-leksi-grand',
    name: 'Супермаркет Лекси - ТЦ Гранд',
    type: 'supermarket',
    city: 'Пловдив',
    address: 'ТЦ Гранд, ул. Капитан Райчо Николов 56',
    coordinates: { lat: 42.1354, lng: 24.7453 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 22:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo', 'izvara'],
    description: 'Пълна гама продукти Бачо Илия',
  },
  {
    id: 'plovdiv-leksi-maritsa',
    name: 'Супермаркет Лекси - Марица',
    type: 'supermarket',
    city: 'Пловдив',
    address: 'бул. Марица 19',
    coordinates: { lat: 42.14, lng: 24.75 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 22:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo', 'izvara'],
  },
  {
    id: 'plovdiv-leksi-peshersko',
    name: 'Супермаркет Лекси - Пещерско шосе',
    type: 'supermarket',
    city: 'Пловдив',
    address: 'бул. Пещерско шосе 78',
    coordinates: { lat: 42.125, lng: 24.76 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 22:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo', 'izvara'],
  },
  {
    id: 'plovdiv-sani',
    name: 'Супермаркет Сани',
    type: 'supermarket',
    city: 'Пловдив',
    address: 'ул. Царевец 14',
    coordinates: { lat: 42.138, lng: 24.748 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 22:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'plovdiv-fresh-silivria',
    name: 'Фрешмаркет - Силиврия',
    type: 'supermarket',
    city: 'Пловдив',
    address: 'ул. Силиврия 15А',
    coordinates: { lat: 42.142, lng: 24.752 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 07:30 - 22:30',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'plovdiv-fresh-elin-pelin',
    name: 'Фрешмаркет - Елин Пелин',
    type: 'supermarket',
    city: 'Пловдив',
    address: 'ул. Елин Пелин 30',
    coordinates: { lat: 42.145, lng: 24.755 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 07:30 - 22:30',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'plovdiv-slanchevi',
    name: 'Слънчеви лъчи',
    type: 'local-shop',
    city: 'Пловдив',
    address: 'бул. Никола Вапцаров 23',
    coordinates: { lat: 42.132, lng: 24.742 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo', 'izvara'],
  },

  // Варна - магазини
  {
    id: 'varna-bakalov',
    name: 'Магазин Бакалов - Колхозен пазар',
    type: 'market',
    city: 'Варна',
    address: 'Колхозен пазар',
    coordinates: { lat: 43.2047, lng: 27.9202 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 06:00 - 16:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo', 'izvara'],
    description: 'Пресни млечни продукти на пазарни цени',
  },
  {
    id: 'varna-ival',
    name: 'Магазин Ивал',
    type: 'local-shop',
    city: 'Варна',
    address: 'ул. Капитан Райчо 11',
    coordinates: { lat: 43.2141, lng: 27.9147 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Стара Загора
  {
    id: 'stara-zagora-valdor',
    name: 'Валдор-777',
    type: 'local-shop',
    city: 'Стара Загора',
    address: 'ул. Иван Хаджихристов',
    coordinates: { lat: 42.4258, lng: 25.6346 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'stara-zagora-detelina',
    name: 'Детелина Комерс 2012',
    type: 'local-shop',
    city: 'Стара Загора',
    address: 'ул. Тодор Кандев 1',
    coordinates: { lat: 42.428, lng: 25.636 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Бургас
  {
    id: 'burgas-dinemax',
    name: 'Динемакс',
    type: 'local-shop',
    city: 'Бургас',
    address: 'ул. Сан Стефано 46',
    coordinates: { lat: 42.5048, lng: 27.4626 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'burgas-rosi-moni',
    name: 'Магазин Роси и Мони',
    type: 'local-shop',
    city: 'Бургас',
    address: 'ж.к. Славейков, до бл. 23',
    coordinates: { lat: 42.51, lng: 27.465 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'burgas-magnetik',
    name: 'Магнетик Маркет',
    type: 'local-shop',
    city: 'Бургас',
    address: 'ж.к. Славейков, бл. 178',
    coordinates: { lat: 42.512, lng: 27.467 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Русе
  {
    id: 'ruse-patconi-borisova',
    name: 'Патсони ООД - Борисова',
    type: 'local-shop',
    city: 'Русе',
    address: 'ул. Борисова 88 (Център Юг)',
    coordinates: { lat: 43.8486, lng: 25.9657 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'ruse-patconi-yatra',
    name: 'Патсони ООД - Ятра',
    type: 'local-shop',
    city: 'Русе',
    address: 'ул. Ятра 4 (Възраждане)',
    coordinates: { lat: 43.85, lng: 25.967 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'ruse-patconi-izola',
    name: 'Патсони ООД - Дружба',
    type: 'local-shop',
    city: 'Русе',
    address: 'ул. Изола Планина 10 (Дружба 1)',
    coordinates: { lat: 43.852, lng: 25.969 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'ruse-patconi-tupcha',
    name: 'Патсони ООД - Затворен пазар',
    type: 'market',
    city: 'Русе',
    address: 'ул. Тупча 4 (Затворен пазар)',
    coordinates: { lat: 43.847, lng: 25.964 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 07:00 - 18:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo', 'izvara'],
  },

  // Враца
  {
    id: 'vratsa-svetla',
    name: 'ЕТ Светла Симеонова 99',
    type: 'local-shop',
    city: 'Враца',
    address: 'ул. Драган Цанков 4',
    coordinates: { lat: 43.21, lng: 23.555 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'vratsa-niki',
    name: 'Ники М ЕООД',
    type: 'local-shop',
    city: 'Враца',
    address: 'ул. Иван Данчов 9',
    coordinates: { lat: 43.212, lng: 23.557 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'vratsa-sunrise',
    name: 'Sunrise Dream ООД',
    type: 'local-shop',
    city: 'Враца',
    address: 'ул. Околчица 108',
    coordinates: { lat: 43.208, lng: 23.552 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'vratsa-vobogo',
    name: 'Вобого - Дъбника',
    type: 'local-shop',
    city: 'Враца',
    address: 'ж.к. Дъбника 45',
    coordinates: { lat: 43.215, lng: 23.56 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'vratsa-supermarket-dabnika',
    name: 'Супермаркет Дъбника',
    type: 'supermarket',
    city: 'Враца',
    address: 'ж.к. Дъбника, ул. Околчица',
    coordinates: { lat: 43.216, lng: 23.561 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 21:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'vratsa-kristiya',
    name: 'Кристия',
    type: 'local-shop',
    city: 'Враца',
    address: 'ул. Стоян Заимов 22',
    coordinates: { lat: 43.209, lng: 23.553 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Кюстендил
  {
    id: 'kyustendil-dimeks-kamchiya',
    name: 'Димекс - Милчо Лазаров',
    type: 'local-shop',
    city: 'Кюстендил',
    address: 'ул. Камчия 13',
    coordinates: { lat: 42.285, lng: 22.69 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kyustendil-dimeks-1may',
    name: 'Димекс - Милчо Лазаров',
    type: 'local-shop',
    city: 'Кюстендил',
    address: 'пл. 1 Май',
    coordinates: { lat: 42.287, lng: 22.692 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kyustendil-piperkovtsi',
    name: 'Димекс - Милчо Лазаров',
    type: 'local-shop',
    city: 'Кюстендил',
    address: 'с. Пиперковци',
    coordinates: { lat: 42.29, lng: 22.7 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Монтана
  {
    id: 'montana-largo-antim',
    name: 'Ларго Груп ЕООД - Антим 1',
    type: 'local-shop',
    city: 'Монтана',
    address: 'ул. Антим 1, №1',
    coordinates: { lat: 43.4092, lng: 23.225 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'montana-largo-mladost',
    name: 'Ларго Груп ЕООД - Младост',
    type: 'local-shop',
    city: 'Монтана',
    address: 'ж.к. Младост 2, Обрчалото',
    coordinates: { lat: 43.412, lng: 23.228 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'montana-zhizel-1',
    name: 'Жизел 1',
    type: 'local-shop',
    city: 'Монтана',
    address: 'ул. Парта 51',
    coordinates: { lat: 43.41, lng: 23.226 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'montana-zhizel-2',
    name: 'Жизел 2',
    type: 'local-shop',
    city: 'Монтана',
    address: 'ул. Макгахан 1',
    coordinates: { lat: 43.411, lng: 23.227 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'montana-zhizel-3',
    name: 'Жизел 3',
    type: 'local-shop',
    city: 'Монтана',
    address: 'ул. Йордан Радичков 3',
    coordinates: { lat: 43.408, lng: 23.224 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'montana-bogat-beden-1',
    name: 'Богат Беден',
    type: 'local-shop',
    city: 'Монтана',
    address: 'ул. Никола Вапцаров 6',
    coordinates: { lat: 43.407, lng: 23.223 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'montana-bogat-beden-2',
    name: 'Богат Беден',
    type: 'local-shop',
    city: 'Монтана',
    address: 'ул. Върбан Панов 1',
    coordinates: { lat: 43.409, lng: 23.225 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Видин
  {
    id: 'vidin-kapa',
    name: 'Капа 2020 ЕООД',
    type: 'local-shop',
    city: 'Видин',
    address: 'ул. Христо Ботев 25',
    coordinates: { lat: 43.99, lng: 22.875 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'vidin-adanas',
    name: 'Аданас',
    type: 'local-shop',
    city: 'Видин',
    address: 'ул. Търговска 2',
    coordinates: { lat: 43.992, lng: 22.877 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Петрич
  {
    id: 'petrich-koop',
    name: 'Кооп Магазин',
    type: 'local-shop',
    city: 'Петрич',
    address: 'ул. Капитан Никола Парапанов 2',
    coordinates: { lat: 41.3989, lng: 23.205 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'petrich-kari',
    name: 'Магазин Кари',
    type: 'local-shop',
    city: 'Петрич',
    address: 'ж.к. Симеон, бл. 20',
    coordinates: { lat: 41.4, lng: 23.207 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'petrich-ray',
    name: 'Супермаркет Рай',
    type: 'supermarket',
    city: 'Петрич',
    address: 'ул. Цар Симеон 24',
    coordinates: { lat: 41.401, lng: 23.209 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 21:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'petrich-choki',
    name: 'Магазин Чоки',
    type: 'local-shop',
    city: 'Петрич',
    address: 'ул. Свети Кирил и Методий 22',
    coordinates: { lat: 41.398, lng: 23.204 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Добрич
  {
    id: 'dobrich-smart',
    name: 'Smart Building',
    type: 'local-shop',
    city: 'Добрич',
    address: 'ж.к. Дружба, бл. 56',
    coordinates: { lat: 43.575, lng: 27.828 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Кърджали
  {
    id: 'kardzhali-aldi',
    name: 'Търговска верига Алди-Г',
    type: 'supermarket',
    city: 'Кърджали',
    address: 'Кърджали',
    coordinates: { lat: 41.6492, lng: 25.3789 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 21:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kardzhali-zornitsa',
    name: 'Магазин Зорница',
    type: 'local-shop',
    city: 'Кърджали',
    address: 'ж.к. Възрожденци, бул. Хр. Ботев',
    coordinates: { lat: 41.652, lng: 25.381 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kardzhali-food-42',
    name: 'Хранителен магазин',
    type: 'local-shop',
    city: 'Кърджали',
    address: 'ж.к. Възрожденци, бл. 42',
    coordinates: { lat: 41.651, lng: 25.38 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kardzhali-food-37',
    name: 'Хранителен магазин',
    type: 'local-shop',
    city: 'Кърджали',
    address: 'ж.к. Възрожденци, бл. 37',
    coordinates: { lat: 41.65, lng: 25.379 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kardzhali-trakiya',
    name: 'Магазин Тракия',
    type: 'local-shop',
    city: 'Кърджали',
    address: 'бул. България 52',
    coordinates: { lat: 41.648, lng: 25.377 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kardzhali-aynes-1',
    name: 'Айнес магазини - Осми Октомври',
    type: 'local-shop',
    city: 'Кърджали',
    address: 'ул. Осми Октомври 13',
    coordinates: { lat: 41.649, lng: 25.378 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kardzhali-aynes-2',
    name: 'Айнес магазини - Васил Левски',
    type: 'local-shop',
    city: 'Кърджали',
    address: 'ул. Васил Левски 5',
    coordinates: { lat: 41.647, lng: 25.376 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kardzhali-aynes-3',
    name: 'Айнес магазини - Червена Стена',
    type: 'local-shop',
    city: 'Кърджали',
    address: 'ул. Червена Стена 3',
    coordinates: { lat: 41.646, lng: 25.375 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kardzhali-aynes-4',
    name: 'Айнес магазини - Македония',
    type: 'local-shop',
    city: 'Кърджали',
    address: 'ул. Македония 8',
    coordinates: { lat: 41.645, lng: 25.374 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kardzhali-aynes-osetiya',
    name: 'Айнес магазини - Осетия',
    type: 'local-shop',
    city: 'Кърджали',
    address: 'Комплекс Осетия',
    coordinates: { lat: 41.644, lng: 25.373 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kardzhali-aynes-warehouse',
    name: 'Айнес складова база',
    type: 'specialty',
    city: 'Кърджали',
    address: 'бул. Лозари 99',
    coordinates: { lat: 41.643, lng: 25.372 },
    phone: '+359 885 911 999',
    workingHours: 'Пон-Пет 08:00 - 18:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo', 'izvara'],
  },
  {
    id: 'kardzhali-paradise-1',
    name: 'Парадайз 1',
    type: 'local-shop',
    city: 'Кърджали',
    address: 'кв. Байкал, ул. Чернобузов 28',
    coordinates: { lat: 41.653, lng: 25.382 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'kardzhali-paradise-3',
    name: 'Парадайз 3',
    type: 'local-shop',
    city: 'Кърджали',
    address: 'ж.к. Възрожденци, бл. 62',
    coordinates: { lat: 46540, lng: 25.383 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Несебър
  {
    id: 'nesebar-zhanet-e87',
    name: 'Гранд Маркет Жанет ООД',
    type: 'supermarket',
    city: 'Несебър',
    address: 'Е87',
    coordinates: { lat: 42.6583, lng: 27.735 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 22:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Харманли
  {
    id: 'harmanli-alan',
    name: 'Алан Маркет ООД',
    type: 'local-shop',
    city: 'Харманли',
    address: 'ул. Марин Велев 1',
    coordinates: { lat: 41.933, lng: 25.902 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'harmanli-gabriela',
    name: 'Габриела-Габи-2019 ЕООД',
    type: 'local-shop',
    city: 'Харманли',
    address: 'бул. България 82',
    coordinates: { lat: 41.935, lng: 25.904 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'harmanli-shans',
    name: 'Шанс-16',
    type: 'local-shop',
    city: 'Харманли',
    address: 'ул. Стратцин 16',
    coordinates: { lat: 41.934, lng: 25.903 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Свиленград
  {
    id: 'svilengrad-laki',
    name: 'Лаки Комерс ЕООД',
    type: 'local-shop',
    city: 'Свиленград',
    address: 'Свиленград',
    coordinates: { lat: 41.7686, lng: 26.2 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'svilengrad-zhanet',
    name: 'Жанет ООД',
    type: 'local-shop',
    city: 'Свиленград',
    address: 'ул. Сан Стефано 1',
    coordinates: { lat: 41.77, lng: 26.202 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 20:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Дупница
  {
    id: 'dupnitsa-izgrev',
    name: 'Супермаркет Изгрев',
    type: 'supermarket',
    city: 'Дупница',
    address: 'ул. Патриарх Евтимий 1 (Стари блокове)',
    coordinates: { lat: 42.2667, lng: 23.1167 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 21:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Бяла (Русе)
  {
    id: 'byala-patconi',
    name: 'Патсони ООД',
    type: 'local-shop',
    city: 'Бяла',
    address: 'ул. Панайот Волов 9',
    coordinates: { lat: 43.4667, lng: 25.7333 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Попово
  {
    id: 'popovo-patconi',
    name: 'Патсони ООД',
    type: 'local-shop',
    city: 'Попово',
    address: 'ул. Дравя 3',
    coordinates: { lat: 43.35, lng: 26.2333 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Кубрат
  {
    id: 'kubrat-patconi',
    name: 'Патсони ООД',
    type: 'local-shop',
    city: 'Кубрат',
    address: 'ул. Цар Освободител 20',
    coordinates: { lat: 43.7833, lng: 26.5 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Тутракан
  {
    id: 'tutrakan-patconi',
    name: 'Патсони ООД',
    type: 'local-shop',
    city: 'Тутракан',
    address: 'ул. Гео Милев 3',
    coordinates: { lat: 44.05, lng: 26.6167 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },

  // Ивайловград
  {
    id: 'ivaylovgrad-zehtendzhievi',
    name: 'Зехтенджиеви ООД',
    type: 'local-shop',
    city: 'Ивайловград',
    address: 'ул. Петко Войвода 23',
    coordinates: { lat: 41.5333, lng: 26.1167 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
  {
    id: 'ivaylovgrad-laki',
    name: 'Лаки 7 ЕООД',
    type: 'local-shop',
    city: 'Ивайловград',
    address: 'ул. Капитан Петко 8',
    coordinates: { lat: 41.535, lng: 26.118 },
    phone: '+359 885 911 999',
    workingHours: 'Всеки ден 08:00 - 19:00',
    products: ['byalo-sirene', 'kashkaval', 'kiselo-mlyako', 'maslo'],
  },
];

// Helper functions
export function getAllStores(): StoreLocation[] {
  return stores;
}

export function getStoresByCity(city: string): StoreLocation[] {
  return stores.filter((store) => store.city === city);
}

export function getAllCities(): string[] {
  const cities = stores.map((store) => store.city);
  return [...new Set(cities)].sort();
}

export function getStoresByProduct(productId: string): StoreLocation[] {
  return stores.filter((store) => store.products.includes(productId));
}

export function searchStores(query: string): StoreLocation[] {
  const lowerQuery = query.toLowerCase();
  return stores.filter(
    (store) =>
      store.name.toLowerCase().includes(lowerQuery) ||
      store.city.toLowerCase().includes(lowerQuery) ||
      store.address.toLowerCase().includes(lowerQuery)
  );
}
